name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: Build and push Docker image
      run: |
        VERSION="${GITHUB_REF_NAME#v}"
        docker build . --file Dockerfile --tag diamondcoder295/giffavs:$VERSION
        docker tag diamondcoder295/giffavs:$VERSION diamondcoder295/giffavs:latest
        docker push diamondcoder295/giffavs:$VERSION
        docker push diamondcoder295/giffavs:latest
